# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-18 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsize',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemsize',
            name='size',
        ),
        migrations.AddField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(to='app.Size'),
        ),
        migrations.DeleteModel(
            name='ItemSize',
        ),
    ]
